#! /usr/bin/env python
from future import standard_library
standard_library.install_aliases()

import os
import csv
import requests
from subprocess import check_output
from collections import defaultdict


wildcard_constraints:
    proj_acc = "[SED]RP[0-9]{6,9}",
    exp_acc  = "[SED]RX[0-9]{6,9}",
    samp_acc = "[SED]RS[0-9]{6,9}",
    run_acc  = "[SED]RR[0-9]{6,9}"

configfile: "config.yaml"

with open(config['sra_run_table'], 'r') as csvfile:
    dialect = csv.Sniffer().sniff(csvfile.read(1024))
    csvfile.seek(0)
    METADATA = [row for row in csv.DictReader(csvfile)]

SAMPLES = [d[config['colname_SAMPLE']] for d in METADATA]

SAMPLE_RUN = defaultdict(list)
for d in METADATA:
    SAMPLE_RUN[d[config['colname_SAMPLE']]].append(d[config['colname_RUN']])


localrules: all
rule all:
    input:
        expand("runs/{run_acc}/completed.txt", run_acc=SAMPLE_RUN[wildcards.samp_acc])

include: "runs.smk"
