#! /usr/bin/env python
## -*- coding: utf-8 -*-

from snakemake.exceptions import WorkflowError

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/get_fastq_files.smk"
include: "rules/align_multi_starsolo.smk"
include: "rules/canonicalQC.smk"
include: "rules/stellarscope.smk"
include: "rules/analysis.smk"

modes = ['pseudobulk','celltype','celltype.l1']

rule all:
    input:
        expand('results/rna_gex_PRJNA587486/analysis/{samp}/{exptag}.sct.h5seurat', samp=dsets.loc['rna_gex_PRJNA587486']['sample'], exptag = modes)

# figure out cite and vdj raw reads
#
#rule all:
#    input:
#        expand('results/rna_gex_PRJNA587486/analysis/{samp}/{exptag}.sct.h5seurat', samp=dsets.loc['rna_gex_PRJNA587486']['sample'], exptag = modes
#        ),
#        expand('results/cite_gex_PRJNA587486/analysis/{samp}/{exptag}.sct.h5seurat', samp=dsets.loc['cite_gex_PRJNA587486']['sample'], exptag = modes
#        ),
#        expand('results/vdj_gex_PRJNA779703/analysis/{samp}/{exptag}.sct.h5seurat', samp=dsets.loc['vdj_gex_PRJNA779703']['sample'], exptag = modes
#        )
