# this file contains everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples file that contains
# one row per sample that can easily be parsed via pandas.

# Path to file containing run-level metadata
# Usually it is a table from SRA Run Selector
#
sra_runtable:
    filename: "config/SraRunTable.csv"
    runid: "Run"
    sampid: "GEO_Accession (exp)"
    layout: "LibraryLayout"

# Samples metadata file
#
samples_metadata:
    filename: "config/gcb_samples_metadata.csv"
    project_meta: "sra_bioproject"
    sampid_meta: "geo_accession"
    sampname_meta: "geo_sample"
    assay_meta: "assay"
    chem_meta: "chemistry"

 
# Path to key for dbGaP protected files.
# Set to null if not using protected files
dbgap_key: null

# directory for temps
#
tmpdir: "/tmp"

# get fastqs rule
#
sra_to_fastq_threads: 8

# 10x protocols
#
barcode_mate:
    v1.1: 'R2'
    v2: 'R1'
    v3: 'R1'

whitelist:
# maybe bioproject as dataset wont be enough     
# yes it will, we just have to know what to ask for

# Downloads
#
downloads:
  whitelist.10x.v3.txt.gz:
    url: "https://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/3M-february-2018.txt.gz"
    md5: "eac3cdd869867e9e979d5da300a81823"
  whitelist.10x.v2.txt:
    url: "https://raw.githubusercontent.com/10XGenomics/cellranger/master/lib/python/cellranger/barcodes/737K-august-2016.txt"
    md5: "f62a276e262fdd85262a889d0f48556b"

whitelist:
  v3: "refs/downloads/whitelist.10x.v3.txt"
  v2: "refs/downloads/whitelist.10x.v2.txt"

