# this file contains everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples file that contains
# one row per sample that can easily be parsed via pandas.

# Path to file containing run-level metadata
# Usually it is a table from SRA Run Selector
#
sra_runtable:
    filename: "config/SraRunTable.csv"
    runid: "Run"
    sampid: "GEO_Accession (exp)"
    layout: "LibraryLayout"
    project: "BioProject"

# Samples metadata file
#
samples_metadata:
    filename: "config/gcb_samples_metadata.csv"
    sampid_meta: "geo_accession"
    sampname_meta: "geo_sample"
    samptype_meta: "data_type"
    tenxtag_meta: "kit"
    tenxchem_meta: "chemistry"

 
# Path to key for dbGaP protected files.
# Set to null if not using protected files
dbgap_key: null

# directory for temps
#
tmpdir: "/tmp"

# Downloads
#
downloads:
  GRCh38.d1.vd1.fa.tar.gz:
    url: "https://api.gdc.cancer.gov/data/254f697d-310d-4d7d-a27b-27fbf767a834"
    md5: "3ffbcfe2d05d43206f57f81ebb251dc9"
  gencode.v38.annotation.gtf.gz:
    url: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.annotation.gtf.gz"
    md5: "16fcae8ca8e488cd8056cf317d963407"
  whitelist.10x.v3.txt.gz:
    url: "https://github.com/10XGenomics/cellranger/raw/master/lib/python/cellranger/barcodes/3M-february-2018.txt.gz"
    md5: "eac3cdd869867e9e979d5da300a81823"
  whitelist.10x.v2.txt:
    url: "https://raw.githubusercontent.com/10XGenomics/cellranger/master/lib/python/cellranger/barcodes/737K-august-2016.txt"
    md5: "f62a276e262fdd85262a889d0f48556b"
  retro.hg38.v1.gtf:
    url: "https://github.com/mlbendall/telescope_annotation_db/raw/master/builds/retro.hg38.v1/transcripts.gtf"
    md5: "c07cf115c1f957b3020efc547f3847fa"
  retro.hg38.v1.tsv.gz:
    url: "https://github.com/mlbendall/telescope_annotation_db/raw/master/builds/retro.hg38.v1/genes.tsv.gz"
    md5: "b3ca6d3705d030742255d216e25dfc1d"

whitelist:
  v3: "refs/downloads/whitelist.10x.v3.txt"
  v2: "refs/downloads/whitelist.10x.v2.txt"

sequences:
    genome: "refs/sequences/genome.fa.gz"
    genome_idx: "refs/sequences/genome.fa.gz.fai"
    genome_dict: "refs/sequences/genome.dict"
    transcripts: "refs/sequences/transcripts.fa"
    transcripts_list: "refs/sequences/transcripts_list.txt"
    transcripts_dupinfo: "refs/sequences/dupinfo.txt"

indexes:
    star: "refs/index.star/genome"

annotations:
    gencode: "refs/downloads/gencode.v38.annotation.gtf.gz"
    retro: "refs/annotation/retro.gtf"
    retro_tsv: "refs/annotation/retro.tsv"
    ttg: "refs/annotation/ttg.tsv"
    gsym: "refs/annotation/gsym.tsv"

# fasterq dump parameters
fasterq_dump_tmp: "$TMPDIR"

# samtools collate parameters
samtools_collate_threads: 24

# STAR genome index parameters
splice_junction_overhang: 74
star_index_threads: 24
star_index_mem_mb: 40000
local_tmp: "$TMPDIR"

# STAR alignment parameters
cellbarcode_start: 1
cellbarcode_length: 16
umi_start: 17
umi_length: 10
max_multimap: 500
star_alignment_threads: 24

# TELESCOPE
telescope_threads: 3

# CELL SORT

cell_sort_tmp: "/local/"
