# this file contains everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples file that contains
# one row per sample that can easily be parsed via pandas.

# Path to file containing run-level metadata
# Usually it is a table from SRA Run Selector
#
sra_runtable:
    filename: "config/SraRunTable.csv"
    runid: "Run"
    sampid: "GEO_Accession (exp)"
    layout: "LibraryLayout"

# Samples metadata file
#
samples_metadata:
    filename: "config/gcb_samples_metadata.csv"
    sampid_meta: "geo_accession"
 
# Path to key for dbGaP protected files.
# Set to null if not using protected files
dbgap_key: null

# directory for temps
#
tmpdir: "/tmp"

# get fastqs rule
#
sra_to_fastq_threads: 8

# reference genome
#
star_index: "resources/STAR_GRCh38.d1.vd1_gencode.v38"

# 10x protocols
#
barcode_mate:
    v1.1: 'R2'
    v2: 'R1'
    v3: 'R1'

whitelist:
    rna_gex_PRJNA587486:
        "resources/whitelist/737K-august-2016.txt"
    cite_gex_PRJNA587486:
        "resources/whitelist/3M-february-2018.txt"
    vdj_gex_PRJNA779703:
        "resources/whitelist/737K-august-2016.txt"

align_multi_starsolo:
    rna_gex_PRJNA587486:
        soloType: "CB_UMI_Simple"
        readFilesCommand: "gunzip -c"
        soloCBstart: 1
        soloCBlen: 16
        soloUMIstart: 17
        soloUMIlen: 10
        outSAMunmapped: "Within"
        soloFeatures: "Gene SJ Velocyto"
        outSAMattributes: "NH HI AS NM nM MD CR CY UR UY CB UB GX GN sS sQ sM"
        outSAMtype: "BAM SortedByCoordinate"
        clipAdapterType: "CellRanger4"
        outFilterScoreMin: 30
        soloCBmatchWLtype: "1MM_multi_Nbase_pseudocounts"
        soloUMIfiltering: "MultiGeneUMI_CR"
        soloUMIdedup: "1MM_CR"
        limitOutSJcollapsed: 5000000
        outFilterMultimapScoreRange: 5
        outFilterMultimapNmax: 500
        limitBAMsortRAM: 47378804544
    cite_gex_PRJNA587486:
        soloType: "CB_UMI_Simple"
        readFilesCommand: "gunzip -c"
        soloBarcodeReadLength: 101
        soloCBstart: 1
        soloCBlen: 16
        soloUMIstart: 17
        soloUMIlen: 12
        outSAMunmapped: "Within"
        soloFeatures: "Gene SJ Velocyto"
        outSAMattributes: "NH HI AS NM nM MD CR CY UR UY CB UB GX GN sS sQ sM"
        outSAMtype: "BAM SortedByCoordinate"
        clipAdapterType: "CellRanger4"
        outFilterScoreMin: 30
        soloCBmatchWLtype: "1MM_multi_Nbase_pseudocounts"
        soloUMIfiltering: "MultiGeneUMI_CR"
        soloUMIdedup: "1MM_CR"
        limitOutSJcollapsed: 5000000
        outFilterMultimapScoreRange: 5
        outFilterMultimapNmax: 500
        limitBAMsortRAM: 47378804544
    vdj_gex_PRJNA779703:
        soloType: "CB_UMI_Simple"
        readFilesCommand: "gunzip -c"
        soloCBstart: 1
        soloCBlen: 16
        soloUMIstart: 17
        soloUMIlen: 10
#        soloBarcodeMate: 1
#        clip5pNbases: "39 -"
        soloStrand: "Reverse"
        outSAMunmapped: "Within"
        soloFeatures: "Gene SJ Velocyto"
        outSAMattributes: "NH HI AS NM nM MD CR CY UR UY CB UB GX GN sS sQ sM"
        outSAMtype: "BAM SortedByCoordinate"
        clipAdapterType: "CellRanger4"
        outFilterScoreMin: 30
        soloCBmatchWLtype: "1MM_multi_Nbase_pseudocounts"
        soloUMIfiltering: "MultiGeneUMI_CR"
        soloUMIdedup: "1MM_CR"
        limitOutSJcollapsed: 5000000
        outFilterMultimapScoreRange: 5
        outFilterMultimapNmax: 500
        limitBAMsortRAM: 47378804544

stellarscope:
        retro_gtf: "resources/retro.hg38.v1.gtf"
        retro_rds: "resources/retro.hg38.v1.rds"
        gtype_rds: "resources/gencode.v38/metadata.gid_gtype.rds"

annotate_celltypes_azimuth:
        filter_threshold: 0.8


