# Path to file containing run-level metadata
# Usually it is a table from SRA Run Selector
sra_run_table: "config/SraRunTable.txt"

# Column names for sample and run
colname_SAMPLE: "BioSample"
colname_RUN: "Run"

# Path to key for dbGaP protected files
# Set to null if not using protected files
dbgap_key: null

# Location for SRA URL.
# Typical options are "ncbi", "s3.us-east-1", "gs.US", etc.
sra_location: "ncbi"

tmpdir: "$TMPDIR"

# SRA to fastq rule input

indir: "/fsx/projects/GCB_FASTQ/{run_acc}/{run_acc}.sra"

# Remote databases or resources to be downloaded
remotefiles:
  GRCh38.d1.vd1.fa.tar.gz:
    url: "https://api.gdc.cancer.gov/data/254f697d-310d-4d7d-a27b-27fbf767a834"
    md5: "3ffbcfe2d05d43206f57f81ebb251dc9"
  gencode.v38.annotation.gtf.gz:
    url: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.annotation.gtf.gz"
    md5: "16fcae8ca8e488cd8056cf317d963407"
  whitelist.10x.v2.txt:
    url: "https://raw.githubusercontent.com/10XGenomics/cellranger/master/lib/python/cellranger/barcodes/737K-august-2016.txt"
    md5: "f62a276e262fdd85262a889d0f48556b"

# STAR genome index parameters
splice_junction_overhang: 74

local_tmp: "$TMPDIR"

# STAR alignment parameters
cellbarcode_start: 1
cellbarcode_length: 16
umi_start: 17
umi_length: 10
max_multimap: 500
