# Use an official R runtime as a parent image
FROM r-base:4.3.0

LABEL maintainer="Helena Reyes-Gopar <hreypar@gmail.com>"

# Set environment variable to avoid interactive prompts during package installation
#ENV R_REMOTES_NO_ERRORS_FROM_WARNINGS=true

# Install necessary system libraries including libhdf5-dev
RUN apt-get update \
    && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev libxml2-dev \
    libfontconfig1-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libhdf5-dev \
    libcairo2-dev \
    libudunits2-dev \
    gdal-bin \
    libgdal-dev 

# Install necessary R packages from cran
RUN Rscript -e "install.packages('remotes', dependencies=TRUE, repos='https://cran.itam.mx/')"
RUN Rscript -e "install.packages(c('tidyverse', 'BiocManager', 'hdf5r', 'sf'), dependencies=TRUE, repos='https://cran.itam.mx/')"
RUN Rscript -e "install.packages('Seurat', version='4.3.0', dependencies=TRUE, repos='https://cran.itam.mx/')"
RUN Rscript -e "install.packages(c('googlesheets4', 'scCustomize', 'ggsci', 'see', 'ggpp', 'future'), dependencies=TRUE, repos='https://cran.itam.mx/')"

# Install necessary R packages from github
RUN Rscript -e "remotes::install_github('mojaveazure/seurat-disk')"
RUN Rscript -e "remotes::install_github('satijalab/seurat-data')"
RUN Rscript -e "remotes::install_github('satijalab/azimuth', ref='master')"
RUN Rscript -e "remotes::install_github('chris-mcginnis-ucsf/DoubletFinder')"

# Install necessary R packages from bioconductor
RUN Rscript -e "BiocManager::install(c('scater', 'Nebulosa', 'Mast', 'glmGamPoi'), dependencies = TRUE, update=TRUE)"

